#
# pipeline_cellbender.py configuration file
# =========================================
#

# General options
# ---------------

# Project name
projectname: Cellbender

# Author
author: Sansom lab

cellhub:
  # The folder containing the cellhub instance
  # where cellranger has been run.
  # It is recommended to start a cellhub run with cellbender 
  # in clean folder so that it can be compared with the 
  # uncorrected results.
  location: ../cellhub

# compute resource options
# ------------------------
resources:

  # amount of memory
  memory: 64G
  
  # number of cpus
  ncpu: 8
    
  # Is memory allocated by core on the cluster?
  # If not, set to "False"
  # If true, set to the integer value of the avaliable
  #    memory/core, e.g. 16 for 16GB.
  # mempercore: 16


# Cellbender parameters
# ---------------------
cellbender:
    # Possible choices: naive, simple, ambient, swapping, full
    model: full
    # cuda -  Include this flag to be run on a GPU.
    cuda: False
    # nepochs
    epochs: 150
    # fpr
    fpr: 0.01
    # learning rate
    learning_rate: 0.0001
    # low count threshold
    low_count_threshold: 5
    # Additional columns from the sample table (input_samples.txt) to show in summary heatmaps
    # If 'none': only exp_batch, channel_id, and seq_batch will be shown (only if they have more than one level)
    # Options: 'all' or comma-separated column names (e.g 'genotype,tissue,sex')
    plot_annotation: all

# Per sample parameters (Add as many entries as needed)
# ---------------------
samples:
  # Replace with the library name indicated in the original "libraries.tsv" table 
  # --expected_cells: Number of cells expected in the dataset (a rough estimate within a factor of 2 is sufficient).
  # --total_droplets_included: The number of droplets from the rank-ordered UMI plot that will have their cell probabilities inferred as an output. Include the droplets which might contain cells. Droplets beyond TOTAL_DROPLETS_INCLUDED should be ‘surely empty’ droplets.
  sample_1:
    expected_cells:
    total_droplets_included:

