#
# pipeline_ambient_rna.py configuration file
# =========================================
#

# General options
# ---------------

# Project name
projectname: scRNAseq analyse ambient RNA profiles

# Author
author: COMBATOxford


# compute resource options
# ------------------------
resources:
    # job memory for tasks; use this in combination with nslots
    # if no slots with memory pre-assigned; 'none' | e.g. 16G (x nslots)
    job_memory: none
    # number of job threads/slots
    threads: 6


# Ambient RNA options
# ------------------------
ambientRNA:
    # Maximum UMI count threshold to define an ambient droplet
    umi: 100
    # Additional columns from the sample table (input_samples.txt) to show in summary heatmaps
    # If 'none': only exp_batch, channel_id, and seq_batch will be shown (only if they have more than one level)
    # Options: 'all' or comma-separated column names (e.g 'genotype,tissue,sex')
    plot_annotation: pool_id
