# vim: ft=smk

import os
from snakemake.exceptions import WorkflowError

TARGET = config["target"]
if TARGET not in ["annotation", "cluster"]:
    raise WorkflowError(f"Unknown module {TARGET} to be run.")

MODE = config.get("mode", "make")
if MODE not in ["make", "config"]:
    raise WorkflowError(f"Unknown mode {MODE} to be run.")

if MODE == "make":
    cfg = f"config_{TARGET}.yml"
    if not os.path.exists(cfg):
        raise WorkflowError(
            f"Config file {cfg} not found.\nPlease rerun with `cellhub {TARGET} config`."
        )

    configfile: cfg


module chosen:
    snakefile:
        (
            workflow.source_path(f"modules/{TARGET}.smk")
            if MODE == "make"
            else workflow.source_path(f"modules/copy_yaml.smk")
        )
    config:
        config


use rule * from chosen
